### ISSUE TITLE
Sort operator for read APIs

### ISSUE THREAD

**Issue by ovaistariq** [tigrisdata/tigris-client-go#223]
Server-side support already exists for this

**Comment by ovaistariq** [comment]
This is for the API documented here: https://www.tigrisdata.com/docs/sdkstools/golang/database/query/

**Comment by Shubham8287** [comment]
Hi @efirs, @ovaistariq.
As you mentioned, Server side support is already implemented and We do not have to perform Sort on sdk. I am guessing that we need to make a change in GRPC and HTTP queries to the server. 

most probably here - https://github.com/tigrisdata/tigris-client-go/blob/main/driver/grpc.go#L397 and then all the "Read" related functions.

If this is the case, Can you show me the query format server expects to Sort?

**Comment by efirs** [comment]
There two levels where it needs to be added:
* driver
* high level client

= Driver = 
driver.ReadOptions need to be converted to a struct (instead of aliasing to api.ReadRequestOptions)
Sort field of type []byte need to be added to this struct.
This struct need to be converted to api.ReadRequestOptions in readWithOptions in grpc.go and http.go
and Sort field passed as part of api.ReadRequest and apiHTTP.TigrisReadJSONRequestBody

== High level client ==
There is already sort field type and helpers in sort/sort.go 
So Sort field of type sort.Order need to be added to tigris.ReadOptions
Sort will be passed like:
```
tigris.ReadOptions{
  Sort: sort.NewSortOrder(sort.Ascending("field1"))
}
```
In the Collection.ReadWithOption sort.Order need to be serialized, using sort.Order.Built function and passed to driver.ReadOptions (here we added Sort field in the driver section above).

Let me know if you need more information.

**Comment by Shubham8287** [comment]
I think understood most of it, I setup the repo locally and ran tests. Start the hacking today, Will ask you questions if needed. Thanks!

**Comment by ovaistariq** [comment]
That's awesome @Shubham8287
